# Generated by Django 5.0 on 2023-12-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('pw', models.CharField(max_length=500)),
                ('Phone_number', models.CharField(max_length=500)),
                ('v_code', models.CharField(max_length=500, unique=True)),
                ('v_statas', models.CharField(max_length=500)),
            ],
        ),
    ]
